import { Geist, Geist_Mono } from "next/font/google";
import {
  Inter,
  Playfair_Display,
  Poppins,
  Reddit_Sans
} from 'next/font/google';
import "./globals.css";


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  style: ['normal', 'italic'],
  variable: '--font-playfair',
  display: 'swap',
});

const poppins = Poppins({
  weight: ['400', '500', '600', '700'], // Add the weights you need
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
});

const redditSans = Reddit_Sans({
  subsets: ['latin'],
  variable: '--font-reddit-sans',
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`
      ${geistSans.variable} 
      ${geistMono.variable} 
      ${inter.variable} 
      ${playfair.variable} 
      ${poppins.variable} 
      ${redditSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
